### ISSUE TITLE
디자인 적용

### ISSUE THREAD

**Issue by lvolzdev** [Blueming-PDA/Blueming#52]
서비스의 전체적인 디자인 적용이 필요.
페이지 별로 디자인을 통일해야 합니다.

# Task
디자인 작업 완료 후, 아래 태스크에 체크 표시를 해주시면 감사하겠습니다.

## bar
- [x] Header
- [x] Sidebar
- [x] Sidebar에 자유게시판을 게시판으로 수정
- [x] Footer

## user 부분
- [x] 로그인
- [x] 로그아웃
- [x] 마이페이지

## page
- [x] 메인 페이지
- [x] 게시판 리스트 (게시판, 과제함, 공지사항)
- [x] 게시판 작성 (게시판, 과제함, 공지사항)
- [ ] 설정

## 메인 기능 관련
- [x] 질문하기 버튼 클릭 시 나타나는 모달창
- [x] 질문보기 모달창에 쌓이는 알림 스택
- [x] 화면 공유 버튼 클릭 시 디자인

**Comment by lvolzdev** [comment]
설정 페이지 -> 소개 페이지로 변경
