### ISSUE TITLE
문서 작업

### ISSUE THREAD

**Issue by lvolzdev** [Blueming-PDA/Blueming#75]
# Task
- [ ] Github README.md 작성
- [x] 프로젝트 구조도 생성
- [ ] ERD 다이어그램 재작성
- [ ] 기술 스택 정리
- [ ] 케이스스터디 정리

**Comment by lvolzdev** [comment]
#85 이슈로 이관했습니다.
